services:
  piano:
    build: .
    ports:
      - "4444:8080"
    volumes:
      - piano_data:/app/data
      - /volume1/docker/Piano/Backups:/backups
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1

volumes:
  piano_data:
